server:
  port: ${APP_PORT:8080}

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true

logging:
  pattern:
    level: '%5p [${spring.application.name}, ${spring.profiles.active}]'
  file:
    name: ${LOG_PATH:.}/app.log

info:
  app:
    name: ${spring.application.name}
    description: Spring Boot Application
    environment: ${spring.profiles.active}
    version: '@project.version@' # Reading From Pom